global with sharing class OpportunityOffer 
{
    global String OfferID {get; set;}
    global Decimal Amount {get; set;}   
    global Decimal DailyCollection {get; set;}      
    global Decimal Duration {get; set;}     
    global String ProductName {get; set;}   
    global Decimal Purchase {get; set;}     
    global Decimal DailyPayment {get; set;}     
    global Decimal NumOfPayments {get; set;}    
    global String ExternalID {get; set;}        
    global String Source {get; set;}    
    global String Notes {get; set;} 
    global Decimal LOC_Fee {get; set;}  
    global Decimal LOC_Limit {get; set;}    
    global Decimal LOC_Drawterm {get; set;} 
    global Decimal LOC_totalterm {get; set;}    
    
}